import type { NextPage } from 'next'
import Head from 'next/head'
import { useTheme } from '@mui/material';
import NoobHeader from '../components/header/noob-header';
import homeModule from '../styles/Home.module.css';


const Home: NextPage = () => {
  const theme = useTheme();
  return (
    <div style={{backgroundColor: theme.palette.background.paper}}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/noob-fav.ico"/>
      </Head>
      <NoobHeader/>
      <main className={homeModule.main}>
        <div>
          Hello
        </div>
      </main>
    </div>
  )
}

export default Home
