INSERT INTO game_platforms ("gameId", "platformId")
VALUES ((SELECT id from games WHERE games.code = 'FIFA_22'), (SELECT id from platforms where platforms.code = 'PS5')),
       ((SELECT id from games WHERE games.code = 'FIFA_22'), (SELECT id from platforms where platforms.code = 'MOBILE')),
       ((SELECT id from games WHERE games.code = 'CSG_O2'), (SELECT id from platforms where platforms.code = 'PC')),
       ((SELECT id from games WHERE games.code = 'CALL_OF_DUTY'), (SELECT id from platforms where platforms.code = 'PS5')),
       ((SELECT id from games WHERE games.code = 'CALL_OF_DUTY'), (SELECT id from platforms where platforms.code = 'PC')),
       ((SELECT id from games WHERE games.code = 'CALL_OF_DUTY'), (SELECT id from platforms where platforms.code = 'MOBILE')),
       ((SELECT id from games WHERE games.code = 'PUBG'), (SELECT id from platforms where platforms.code = 'PC')),
       ((SELECT id from games WHERE games.code = 'PUBG'), (SELECT id from platforms where platforms.code = 'MOBILE')),
       ((SELECT id from games WHERE games.code = 'F1_2021'), (SELECT id from platforms where platforms.code = 'PS5')),
       ((SELECT id from games WHERE games.code = 'VALORANT'), (SELECT id from platforms where platforms.code = 'PC')),
       ((SELECT id from games WHERE games.code = 'OVERWATCH'), (SELECT id from platforms where platforms.code = 'PC')),
       ((SELECT id from games WHERE games.code = 'OVERWATCH'), (SELECT id from platforms where platforms.code = 'PS4')),
       ((SELECT id from games WHERE games.code = 'OVERWATCH'), (SELECT id from platforms where platforms.code = 'XBOX')),
       ((SELECT id from games WHERE games.code = 'DOTA_2'), (SELECT id from platforms where platforms.code = 'PC')),
       ((SELECT id from games WHERE games.code = 'MORTAL_KOMBAT_X'), (SELECT id from platforms where platforms.code = 'PS5')),
       ((SELECT id from games WHERE games.code = 'MORTAL_KOMBAT_X'), (SELECT id from platforms where platforms.code = 'XBOX')),
       ((SELECT id from games WHERE games.code = 'FORTNITE'), (SELECT id from platforms where platforms.code = 'PS4')),
       ((SELECT id from games WHERE games.code = 'FORTNITE'), (SELECT id from platforms where platforms.code = 'MOBILE')),
       ((SELECT id from games WHERE games.code = 'FORTNITE'), (SELECT id from platforms where platforms.code = 'XBOX')),
       ((SELECT id from games WHERE games.code = 'APEX_LEGENDS'), (SELECT id from platforms where platforms.code = 'PS5')),
       ((SELECT id from games WHERE games.code = 'APEX_LEGENDS'), (SELECT id from platforms where platforms.code = 'PC')),
       ((SELECT id from games WHERE games.code = 'APEX_LEGENDS'), (SELECT id from platforms where platforms.code = 'PS4')),
       ((SELECT id from games WHERE games.code = 'APEX_LEGENDS'), (SELECT id from platforms where platforms.code = 'MOBILE')),
       ((SELECT id from games WHERE games.code = 'APEX_LEGENDS'), (SELECT id from platforms where platforms.code = 'XBOX')),
       ((SELECT id from games WHERE games.code = 'ROCKET_LEAGUE'), (SELECT id from platforms where platforms.code = 'PS5')),
       ((SELECT id from games WHERE games.code = 'ROCKET_LEAGUE'), (SELECT id from platforms where platforms.code = 'PS4')),
       ((SELECT id from games WHERE games.code = 'ROCKET_LEAGUE'), (SELECT id from platforms where platforms.code = 'XBOX'));
